MvcApp/Areas/Admin/Controllers/BookController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing.Constraints;
using MvcApp.EFCore.Models;
using MvcApp.Services;
using MvcApp.Utility;
using System.Collections.Generic;
using System.Linq;
namespace MvcApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    
    public class BookController:Controller
    {
        private readonly IUnitOfWork _uow;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public BookController(IUnitOfWork uow, IWebHostEnvironment webHostEnvironment)
        {
            _uow = uow;
            _webHostEnvironment = webHostEnvironment;
        }
        [Authorize(Roles = Roles.Role_Admin)]
        public async Task<IActionResult> Index()
        {
            return View(await _uow.BookRepository.GetAllAsync(includes:"Category"));
        }
        [Authorize(Roles = Roles.Role_Admin)]
        public async Task<IActionResult> Upsert(int? id)
        {
            IEnumerable<SelectListItem> list = (await _uow.CategoryRepository.GetAllAsync())
            .Select(x => new SelectListItem
            {
                Text = x.Name,
                Value = x.Id.ToString()
            });
            ViewBag.CategoryList = list;
            BookViewModel BookVM = new()
            {
                CategoryList = list,
                book= new Book()
            };
            if(id is null || id == 0)
            {
                // create
                return View(BookVM);
            }
            else
            {
                // update
                BookVM.book = await _uow.BookRepository.GetAsync(x=>x.Id == id);
                return View(BookVM);
            }
        }
        [HttpPost]
        [Authorize(Roles = Roles.Role_Admin)]
        public async Task<IActionResult> Upsert(BookViewModel obj,IFormFile? file,CancellationToken token)
        {
            if (ModelState.IsValid)
            {
                string? wwwRootPath = _webHostEnvironment.WebRootPath;
                if (file is not null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string bookPath = Path.Combine(wwwRootPath, @"Images\Books");

                    if (!string.IsNullOrEmpty(obj.book.ImageUrl))
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, obj.book.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }
                    using (var fileStream = new FileStream(Path.Combine(bookPath, fileName), FileMode.Create))
                    {
                        await file.CopyToAsync(fileStream);
                    }
                    obj.book.ImageUrl =@"\Images\Books\"+fileName;
                }
                if (obj.book.Id == 0)
                {
                    await _uow.BookRepository.CreateAsync(obj.book);
                    await _uow.CommitAsync(token);
                    TempData["success"] = "Book created successfully";
                }
                else
                {
                    await _uow.BookRepository.UpdateAsync(obj.book.Id,obj.book);
                    await _uow.CommitAsync(token);
                    TempData["success"] = "Book updated successfully";
                }
                return RedirectToAction("Index");
            }
            else
            {
                obj.CategoryList = (await _uow.BookRepository.GetAllAsync())
                .Select(x => new SelectListItem
                {
                    Text =  x.Title,
                    Value = x.Id.ToString()
                });
                return View(obj);
            }

           
        }
        
        public async Task<IActionResult> ProgrammingBooks()
        {
            var records = await _uow.BookRepository.GetAllAsync(includes:"Category");
            records = records.Where(x => x.Category.Name.Equals("Programming"));
            return View(records);
        }
        public async Task<IActionResult> MangaBooks()
        {
            var records = await _uow.BookRepository.GetAllAsync(includes: "Category");
            records = records.Where(x => x.Category.Name.Equals("Manga"));
            return View(records);
        }
        public async Task<IActionResult> AIBooks()
        {
            var records = await _uow.BookRepository.GetAllAsync(includes: "Category");
            records = records.Where(x => x.Category.Name.Equals("Artificial Intelligent"));
            return View(records);
        }

        #region APICALL
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var records = await _uow.BookRepository.GetAllAsync(includes: "Category");

            return Json(new {data = records});
        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int id, CancellationToken token)
        {
            
            if (!ModelState.IsValid || id <= 0)
                return Json(new { success = false, message = "error while deleting" });

            var record = await _uow.BookRepository.GetByIdAsync(id);
            if (record is null)
                return Json(new { success = false, message = "error while deleting" });

            var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, 
                record.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }
            await _uow.BookRepository.DeleteAsync(id);
            await _uow.CommitAsync(token);
            TempData["success"] = "book delete successfully";
            return Json(new { success = true, message = "book deleted successfull" });
        }
        #endregion
    }
}

MvcApp/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvcApp.EFCore.Data;
using MvcApp.EFCore.Models;
using MvcApp.Utility;

namespace MvcApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = Roles.Role_Admin)]
    public class UserController:Controller
    {
        private readonly AppDbContext _context;
        
        public UserController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            IQueryable<MvcApp.EFCore.Models.UserView> records = from u in _context.Users
                                                                join ur in _context.UserRoles on u.Id equals ur.UserId
                                                                join r in _context.Roles on ur.RoleId equals r.Id
                                                                select new MvcApp.EFCore.Models.UserView
                                                                {
                                                                    UserName = u.UserName,
                                                                    Email = u.Email,
                                                                    Role = r.Name
                                                                };
            return View(records);

        }
    }
    public class UserView
    {
        public string? UserName { get; set;}
        public string? Email { get; set;}
        public string? Role { get; set;}
    }
}

MvcApp/Areas/Customer/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvcApp.EFCore.Data;
using MvcApp.EFCore.Models;
using MvcApp.EFCore.ViewModel;
using MvcApp.Services;
using MvcApp.Utility;
using System.Linq;

namespace MvcApp.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class CartController:Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly IUnitOfWork _uow;
        public CartController(AppDbContext context,
            UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager,
            IUnitOfWork uow)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
            _uow = uow;
        }

        public async Task<IActionResult> Index()
        {
            var carts = await _uow.ShoppingCartRepository.GetAllAsync(includes:"Book");
            return View(carts);
        }
        [Authorize]
        public async Task<IActionResult> AddToCart(int bookId,CancellationToken token)
        {
            var record = await _context.Set<Book>().FirstOrDefaultAsync(x=>x.Id==bookId);
            if (_signInManager.IsSignedIn(User))
            {
                var user =  _userManager.GetUserId(User);
                if(user is not null)
                {
                    var getCartIfExistInUser = await _context.ShoppingCarts.Where(x => x.UserId.Equals(user)).ToListAsync();
                    if (getCartIfExistInUser.Count()>0)
                    {
                        // User has a cart & updatig the item quantity
                        var getTheQuantity = getCartIfExistInUser.FirstOrDefault(x => x.BookId == bookId);
                        if(getTheQuantity is not null)
                        {
                            getTheQuantity.Quantity += 1;
                            await _uow.ShoppingCartRepository.UpdateAsync(getTheQuantity.Id,getTheQuantity);
                        }
                        else
                        {
                            // User has a cart & adding a new item
                            ShoppingCart cart = new ShoppingCart
                            {
                                BookId = bookId,
                                UserId = user,
                                Quantity =1
                            };
                            await _uow.ShoppingCartRepository.CreateAsync(cart);
                        }
                    }
                    else
                    {
                        // user has no cart & adding a new item
                        ShoppingCart cart = new ShoppingCart
                        {
                            BookId =bookId,
                            UserId=user,
                            Quantity =1 
                        };
                        await _uow.ShoppingCartRepository.CreateAsync(cart);
                    }
                    await _uow.CommitAsync(token);
                }
            }
            return RedirectToAction("Index","Home");
        }
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            
            return Ok(await _uow.ShoppingCartRepository.GetAllAsync(includes:"Book"));
        }
       


        #region APICALL

        public async Task<IActionResult> Delete(int cartId,CancellationToken token)
        {
            var cart = await _uow.ShoppingCartRepository.GetAsync(x => x.Id == cartId, includes: "Book");
            var count = _context.ShoppingCarts.Where(x => x.UserId == cart.UserId).ToList().Count();
            await _uow.ShoppingCartRepository.DeleteAsync(cart.Id);
            await _uow.CommitAsync(token);
            HttpContext.Session.SetInt32(CartCount.sessionCart, count - 1);

            return RedirectToAction("Index");
        }
        #endregion
    }
}

MvcApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Libros Plaza</title>
    <link href="~/css/style.css" rel="stylesheet" />
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" /> *@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" asp-append-version="true">
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="https://cdn.datatables.net/2.0.3/css/dataTables.dataTables.css" asp-append-version="true" /> *@
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Signika+Negative:wght@300..700&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> Libros Plaza</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto text-white">
                        <li class="nav-item text-white">
                            <a class="nav-link text-white" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.IsInRole(Roles.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white"  role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Management Menu
                                </a>
                                <ul class="dropdown-menu ">
                                    <li class="nav-item">
                                        <a class="dropdown-item text-white" asp-area="Admin" asp-controller="Category" asp-action="Index">Categories</a>
                                    </li>
                                    <li class="nav-item ">
                                        <a class="dropdown-item text-white" asp-area="Admin" asp-controller="Book" asp-action="Index">Books</a>
                                    </li>
                                </ul>
                            </li>
                        }
                        <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white"  role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Categories
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="dropdown-item text-white" asp-area="Admin" asp-controller="Book" asp-action="ProgrammingBooks">Programming</a>
                                    </li>
                                    <li class="nav-item">
                                    <a class="dropdown-item text-white" asp-area="Admin" asp-controller="Book" asp-action="MangaBooks">Manga</a>
                                    </li>
                                    <li class="nav-item">
                                    <a class="dropdown-item text-white" asp-area="Admin" asp-controller="Book" asp-action="AIBooks">AI</a>
                                    </li>
                                </ul>
                            </li>
                        @if (User.IsInRole(Roles.Role_Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link " asp-area="Admin" asp-controller="User" asp-action="Index" >Users</a>
                            </li>
                        }
                        @if (HttpContextAccessor.HttpContext.Session.GetInt32(CartCount.sessionCart) != null)
                        {
                            <li class="nav-item">
                                <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="nav-link  " id="cart">
                                    <i class="bi bi-cart-fill "></i>
                                    <span class="badge text-bg-info">
                                        
                                        @{
                                            var count = HttpContextAccessor.HttpContext.Session.GetInt32(CartCount.sessionCart);
                                        }
                                        (@count)
                                    </span>
                                </a>
                            </li>
                        }
                        else
                        {
                        <li class="nav-item">
                            <a href="#" class="nav-link text-dark " id="cart">
                            <span class="badge text-bg-info">(0)</span>
                            <i class="bi bi-cart"></i>
                            </a>
                        </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="https://cdn.tiny.cloud/1/g28lhnxtlihu4l4a381gw7tz47voznshwbi10lmsvlekrfme/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcApp/Views/Shared/_Notification.cshtml
@if (TempData["success"] is not null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script> 
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] is not null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["error"]');
    </script>
}